// Copyright (c) 2026 Innovation Trigger B.V. All rights reserved.
//
// This software is proprietary. The PDFluent application is free to use,
// including for commercial purposes. Redistribution, or extraction or reuse
// of its components (including the embedded PDF engine), requires a licence.
// See https://pdfluent.com/license for terms.

// GENERATED by scripts/quality/ui-register.mjs — do not edit.
//
// The All-tools panel renders a tile only when its `fulfilledBy` claim resolves
// to an affordance that the shipped shell renders and that reaches something.
// Editing this list by hand is how the previous list came to enable tiles with
// no handler and disable tiles that worked; `quality:ui-register` fails when
// this file no longer matches the walk.

/** Tiles whose tool works in every runtime. */
export const WIRED_TILES_ALL_RUNTIMES: readonly string[] = [
  'toolbar.bookmarks',
  'toolbar.comment',
  'toolbar.editText',
  'toolbar.exportPdf',
  'toolbar.freeDraw',
  'toolbar.fullscreen',
  'toolbar.highlight',
  'toolbar.pan',
  'toolbar.searchText',
  'toolbar.select',
  'toolbar.strikethrough',
  'toolbar.underline',
  'toolbar.zoomIn',
  'toolbar.zoomOut',
];

/** Tiles whose tool reaches a Tauri command, so browser-test cannot run them. */
export const WIRED_TILES_TAURI_ONLY: readonly string[] = [
  'toolbar.compress',
  'toolbar.deletePage',
  'toolbar.insertPage',
  'toolbar.invoice',
  'toolbar.merge',
  'toolbar.metadata',
  'toolbar.ocrScan',
  'toolbar.password',
  'toolbar.pdfa',
  'toolbar.readAloud',
  'toolbar.redact',
  'toolbar.rotateLeft',
  'toolbar.rotateRight',
  'toolbar.signature',
  'toolbar.split',
  'toolbar.watermark',
];
