#!/usr/bin/env node
// Copyright (c) 2026 Innovation Trigger B.V. All rights reserved.
//
// This software is proprietary. The PDFluent application is free to use,
// including for commercial purposes. Redistribution, or extraction or reuse
// of its components (including the embedded PDF engine), requires a licence.
// See https://pdfluent.com/license for terms.
//
// report.mjs — turn the rows a run wrote into quality/reports/<version>-<platform>.{json,md}
// and decide the verdict.
//
// The report is rendered from $WORK/steps.ndjson and never from shell
// variables: a step that dies half way leaves the rows it already appended, so
// it shows up as a FAIL row rather than as a row that is simply not there. An
// absent row is the failure mode this whole file exists to make impossible.
//
//   node report.mjs --work <dir> --out quality/reports      # render, print exit code
//   node report.mjs --check quality/reports/1.0.0-macos.json  # re-render and diff
//
// Verdict fold: any FAIL → FAIL (1); else any SKIPPED → INCOMPLETE (3); else
// PASS (0). NOT_APPLICABLE is neither — a build that deliberately ships without
// updater artefacts is a clean 0 and the report says why.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";

export const VERDICTS = {
  PASS: { verdict: "PASS", exit_code: 0 },
  FAIL: { verdict: "FAIL", exit_code: 1 },
  COULD_NOT_RUN: { verdict: "COULD_NOT_RUN", exit_code: 2 },
  INCOMPLETE: { verdict: "INCOMPLETE", exit_code: 3 },
};

export function foldVerdict(steps, { couldNotRun = false } = {}) {
  if (couldNotRun) return VERDICTS.COULD_NOT_RUN;
  if (steps.some((s) => s.status === "FAIL")) return VERDICTS.FAIL;
  if (steps.some((s) => s.status === "SKIPPED")) return VERDICTS.INCOMPLETE;
  return VERDICTS.PASS;
}

const STEP_ORDER = ["S0", "S1", "S2", "S3", "S4", "S5"];

export function buildReport(meta, rawSteps) {
  // Rows are appended as they are judged, and the gaps a platform declares come
  // last. A reader wants them by step, so they are sorted here — stably, so the
  // order within a step is still the order things happened in.
  const steps = [...rawSteps].sort((a, b) => {
    const d = STEP_ORDER.indexOf(a.step) - STEP_ORDER.indexOf(b.step);
    return d !== 0 ? d : 0;
  });
  const { verdict, exit_code } = foldVerdict(steps, { couldNotRun: meta.could_not_run === true });
  return {
    schema: "pdfluent-release-suite/1",
    run_id: meta.run_id,
    source: "artefact",
    version: meta.version,
    platform: meta.platform,
    machine: meta.machine,
    os: meta.os ?? null,
    load1: meta.load1 ?? null,
    artefacts: meta.artefacts ?? { primary: null, updater: null },
    built_from: meta.built_from ?? null,
    suite_commit: meta.suite_commit ?? null,
    tools: meta.tools ?? {},
    golden_set: meta.golden_set ?? null,
    steps,
    not_measured: meta.not_measured ?? [],
    verdict,
    exit_code,
    date: meta.date,
  };
}

const cell = (v) => String(v ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");

export function renderMarkdown(r) {
  const L = [];
  L.push(`# Release quality suite — ${r.version} — ${r.platform}`);
  L.push("");
  L.push("<!-- Generated by scripts/quality/suite/report.mjs. Do not edit: `--check` regenerates this file and diffs it. -->");
  L.push("");
  L.push(`**Verdict: ${r.verdict}** (exit ${r.exit_code}) · run \`${r.run_id}\` · ${r.date}`);
  L.push("");
  L.push("| field | value |");
  L.push("|---|---|");
  L.push(`| artefact | ${cell(r.artefacts?.primary?.name)} |`);
  L.push(`| sha256 | \`${cell(r.artefacts?.primary?.sha256)}\` |`);
  L.push(`| bytes | ${cell(r.artefacts?.primary?.bytes)} |`);
  L.push(`| built from | ${cell(r.built_from?.commit)} (${cell(r.built_from?.asserted_by)}) |`);
  L.push(`| frontend fingerprint | ${cell(r.built_from?.frontend_fingerprint)} |`);
  L.push(`| suite commit | ${cell(r.suite_commit)} |`);
  L.push(`| machine class | ${cell(r.machine)} |`);
  L.push(`| os | ${cell(r.os)} |`);
  L.push(`| golden set | ${cell(r.golden_set?.count)} documents, ${cell(r.golden_set?.verified_by)} |`);
  L.push("");
  L.push("## Steps");
  L.push("");
  L.push("| step | id | capability | status | numbers | reason | evidence |");
  L.push("|---|---|---|---|---|---|---|");
  for (const s of r.steps) {
    const numbers = Object.entries(s.numbers ?? {}).map(([k, v]) => `${k}=${v}`).join(" ");
    L.push(`| ${cell(s.step)} | ${cell(s.id)} | ${cell(s.capability)} | ${cell(s.status)} | ${cell(numbers)} | ${cell(s.reason)} | ${cell((s.evidence ?? []).join(" "))} |`);
  }
  L.push("");
  L.push("## Not measured");
  L.push("");
  if (!r.not_measured.length) L.push("- (nothing)");
  for (const n of r.not_measured) L.push(`- ${n}`);
  L.push("");
  L.push("## Skipped (not a pass)");
  L.push("");
  const skipped = r.steps.filter((s) => s.status === "SKIPPED");
  if (!skipped.length) L.push("- (nothing)");
  for (const s of skipped) L.push(`- \`${s.id}\` — ${s.reason}`);
  L.push("");
  return L.join("\n");
}

export function readSteps(work) {
  const f = path.join(work, "steps.ndjson");
  if (!existsSync(f)) return [];
  return readFileSync(f, "utf8")
    .split("\n")
    .filter((l) => l.trim())
    .map((l) => {
      try { return JSON.parse(l); }
      catch { return { step: "??", id: "unparsable-row", capability: "suite", status: "FAIL", ms: 0, numbers: {}, reason: `a step wrote a row this file could not parse: ${l.slice(0, 120)}`, evidence: [] }; }
    });
}

// ── CLI ──────────────────────────────────────────────────────────────────────
if (import.meta.url === `file://${process.argv[1]}`) {
  const argv = process.argv.slice(2);
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith("--")) {
      const k = argv[i].slice(2);
      const v = argv[i + 1];
      if (v === undefined || v.startsWith("--")) args[k] = true;
      else { args[k] = v; i++; }
    }
  }

  if (args.check && args.check !== true) {
    const jsonPath = path.resolve(String(args.check));
    const mdPath = jsonPath.replace(/\.json$/, ".md");
    const report = JSON.parse(readFileSync(jsonPath, "utf8"));
    const want = renderMarkdown(report);
    const have = existsSync(mdPath) ? readFileSync(mdPath, "utf8") : "";
    if (want !== have) {
      console.error(`✘ ${path.relative(process.cwd(), mdPath)} is not what ${path.basename(jsonPath)} renders to.`);
      console.error("  This file is generated. Re-run the suite, or `node scripts/quality/suite/report.mjs --check <json> --write`.");
      const w = want.split("\n"), h = have.split("\n");
      for (let i = 0; i < Math.max(w.length, h.length); i++) {
        if (w[i] !== h[i]) { console.error(`  line ${i + 1}:\n    generated: ${w[i] ?? "(none)"}\n    on disk:   ${h[i] ?? "(none)"}`); break; }
      }
      if (args.write) { writeFileSync(mdPath, want, "utf8"); console.error("  (rewritten)"); }
      process.exit(1);
    }
    console.log(`✓ ${path.relative(process.cwd(), mdPath)} matches its JSON`);
    process.exit(0);
  }

  const work = String(args.work);
  const meta = JSON.parse(readFileSync(path.join(work, "meta.json"), "utf8"));
  // The updater payload is discovered during S4, after meta.json was written.
  const updaterFile = path.join(work, "updater.json");
  if (existsSync(updaterFile)) {
    try { meta.artefacts = { ...meta.artefacts, updater: JSON.parse(readFileSync(updaterFile, "utf8")) }; }
    catch { /* a payload the suite could not read is already a FAIL row */ }
  }
  const report = buildReport(meta, readSteps(work));
  const outDir = path.resolve(String(args.out || "quality/reports"));
  mkdirSync(outDir, { recursive: true });
  const base = path.join(outDir, `${report.version}-${report.platform}`);
  writeFileSync(`${base}.json`, JSON.stringify(report, null, 2) + "\n", "utf8");
  writeFileSync(`${base}.md`, renderMarkdown(report), "utf8");
  console.log(`${report.verdict} — ${path.relative(process.cwd(), base)}.json`);
  process.exit(report.exit_code);
}
